language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

branches:
  only:
    - master

env: NO_INTERACTION=1

install:
  - phpize
  - ./configure
  - make

before_script:
  - travis_retry ./.travis.sh monolog_init
# it's out of date
#  - travis_retry ./.travis.sh cache_init
  - travis_retry ./.travis.sh psr7_init

script:
  - make test
  - ./.travis.sh monolog_test
# it's out of date
#  - ./.travis.sh cache_test
  - ./.travis.sh psr7_test

